global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'forecasting-service'
    static_configs:
      - targets: ['forecasting-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'optimization-service'
    static_configs:
      - targets: ['optimization-service:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'simulation-service'
    static_configs:
      - targets: ['simulation-service:8003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['db:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
